/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RegistrationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Registration = IDL.Record({
  'id' : IDL.Text,
  'status' : RegistrationStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'upiOrInsta' : IDL.Text,
  'email' : IDL.Text,
  'teamMembers' : IDL.Text,
  'slotId' : IDL.Nat,
  'gameName' : IDL.Text,
  'phone' : IDL.Text,
  'ffUID' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
});
export const TournamentSlot = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'entryFee' : IDL.Nat,
  'prizePool' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'approvePayment' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getTournamentSlots' : IDL.Func([], [IDL.Vec(TournamentSlot)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerForTournament' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'rejectPayment' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'submitPaymentClaim' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RegistrationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Registration = IDL.Record({
    'id' : IDL.Text,
    'status' : RegistrationStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'upiOrInsta' : IDL.Text,
    'email' : IDL.Text,
    'teamMembers' : IDL.Text,
    'slotId' : IDL.Nat,
    'gameName' : IDL.Text,
    'phone' : IDL.Text,
    'ffUID' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const TournamentSlot = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'entryFee' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'approvePayment' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getTournamentSlots' : IDL.Func([], [IDL.Vec(TournamentSlot)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerForTournament' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'rejectPayment' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'submitPaymentClaim' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };