/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Registration {
  'id' : string,
  'status' : RegistrationStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'upiOrInsta' : string,
  'email' : string,
  'teamMembers' : string,
  'slotId' : bigint,
  'gameName' : string,
  'phone' : string,
  'ffUID' : string,
}
export type RegistrationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface TournamentSlot {
  'id' : bigint,
  'name' : string,
  'time' : string,
  'entryFee' : bigint,
  'prizePool' : bigint,
}
export interface UserProfile {
  'age' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'approvePayment' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllRegistrations' : ActorMethod<[], Array<Registration>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyRegistrations' : ActorMethod<[], Array<Registration>>,
  'getTournamentSlots' : ActorMethod<[], Array<TournamentSlot>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerForTournament' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'rejectPayment' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserProfile' : ActorMethod<[string, string, bigint], undefined>,
  'submitPaymentClaim' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];